"""Generate a spoken script for one walkthrough video per project.

Run:
    python3 tools/video_scripts.py

Same rule as tools/docs.py and tools/readme.py: every figure spoken aloud in these scripts
is read from a committed artifact rather than typed. A presenter reading one of these on
camera is therefore saying the same number the site is displaying behind them, and a rerun
of a pipeline updates the script rather than leaving the video contradicting the screen.

Each script is written to be *said*, not read: short sentences, one idea per breath,
contractions, and no clause that needs a second pass to parse. Stage directions are marked
separately from speech so they are never read out by mistake.

Timestamps are computed from a cumulative word count at SPEAKING_WPM, so they shift
automatically when the numbers underneath them change.
"""

from __future__ import annotations

import re
import sys
from dataclasses import dataclass
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "tools"))

from docs import SITE, SLUGS, load, pct  # noqa: E402

OUT = ROOT / "docs" / "video-scripts"

# Unhurried presentation pace. Deliberately below conversational speed: these scripts are
# dense with figures, and a listener needs a beat after each one.
SPEAKING_WPM = 135


@dataclass
class Beat:
    """One spoken passage, with what should be visible while it is said."""
    heading: str
    say: str
    show: str | None = None
    note: str | None = None


def _words(text: str) -> int:
    return len(re.findall(r"[\w'’-]+", text))


def _clock(seconds: float) -> str:
    return f"{int(seconds) // 60}:{int(seconds) % 60:02d}"


def render(project: str, title: str, hook: str, prep: list[str], beats: list[Beat]) -> str:
    """Assemble one script, timestamping each beat from the words spoken before it."""
    slug = SLUGS[project]
    spoken = 0
    body: list[str] = []

    for beat in beats:
        body.append(f"## [{_clock(spoken / SPEAKING_WPM * 60)}] {beat.heading}")
        body.append("")
        if beat.show:
            body.append(f"> **On screen —** {beat.show}")
            body.append("")
        if beat.note:
            body.append(f"> **Note to self —** {beat.note}")
            body.append("")
        body.append(beat.say.strip())
        body.append("")
        spoken += _words(beat.say)

    total_words = spoken
    runtime = _clock(total_words / SPEAKING_WPM * 60)

    prep_lines = "\n".join(f"- {p}" for p in prep)

    return f"""# Video {project[:2]} · {title}

**Estimated runtime:** ~{runtime} at a measured pace ({total_words:,} spoken words)
**Live page:** {SITE}/#/p/{slug}
**Project directory:** [`projects/{project}/`](../../projects/{project}/)

> **The one sentence this video has to land:** {hook}

## Before you record

{prep_lines}

Everything in plain text below is meant to be **spoken**. Lines marked *On screen* and
*Note to self* are directions — do not read them aloud.

---

{chr(10).join(body)}---

*Generated by [`tools/video_scripts.py`](../../tools/video_scripts.py) from committed
artifacts. Every figure spoken here is the figure on screen.*
"""


# ======================================================================================
# 01 — NYC ride-hail demand
# ======================================================================================
def script_01() -> tuple[str, str]:
    project = "01_nyc_mobility"
    prof = load(project, "profile")["profile"]
    models = load(project, "models")
    best = models["models"][models["best_model"]]
    naive = models["models"]["seasonal_naive_168h"]
    split = models["split"]
    conf = models["conformal"]
    c80 = conf["80%"]
    calibrated = [k for k, v in conf.items() if v["calibrated"]]
    failed = [k for k, v in conf.items() if not v["calibrated"]]

    beats = [
        Beat(
            heading="Cold open",
            show="the project page, scrolled to the headline numbers",
            say=f"""
Here's a number I could have put at the top of this project and stopped.

Mean absolute error: {best['mae']:.2f}. R-squared of {best['r2']:.3f}.

On its own, that number is meaningless. And I want to show you why, because it's the
thing that separates a model that works from a model that just looks like it works.
""",
        ),
        Beat(
            heading="The baseline that makes the number mean something",
            show="the model comparison table, with the seasonal-naive row visible",
            say=f"""
Here's the comparison that matters.

The simplest possible forecast for this problem is: whatever happened at this hour last
week, that's my prediction. Same hour, same day of the week, seven days ago. Zero
parameters. No training. You can do it in one line.

That baseline gets a mean absolute error of {naive['mae']:.2f}.

My gradient boosted model gets {best['mae']:.2f}.

So the model is better — but now you can see *how much* better. It's a
{pct(best['skill_score_vs_baseline'])} improvement over doing almost nothing. That's a
real result, and it's a modest one. If I'd only shown you the R-squared, you'd have
assumed something far more impressive.

Every metric on this site is reported next to its no-skill baseline, for exactly this
reason. A score without a reference point isn't a result. It's a number.
""",
        ),
        Beat(
            heading="The data",
            show="the Data provenance tab",
            say=f"""
The data is real. This is {prof['rows_raw']:,} actual taxi and ride-hail dispatch records
from New York City, {prof['date_min'][:10]} through {prof['date_max'][:10]}, released by
the Taxi and Limousine Commission under a freedom of information request.

It's downloaded on first run and pinned by a SHA-256 hash, so if the file upstream ever
changes underneath this project, it fails loudly instead of quietly shifting every number
downstream.

I'm saying that explicitly because the portfolio this work responds to labels its datasets
as coming from Kaggle, and then generates all of them with a random number generator. That
comparison is documented in the repository.
""",
        ),
        Beat(
            heading="One judgement call worth showing",
            show="the provenance panel, duplicate rationale expanded",
            say=f"""
Here's a decision I want to walk through, because the reasoning matters more than the
answer.

There are {prof['exact_duplicates']:,} exact duplicate rows in this data — about
{pct(prof['exact_duplicate_share'])} of it. The reflex is to drop duplicates. It's almost
a habit.

I kept them. Here's why.

The timestamps are recorded to the minute, and the coordinates are rounded to about eleven
metres. So two genuinely different cars, dispatched from the same base, on the same block,
in the same minute, are *indistinguishable* in this schema. They look like a duplicate.
They aren't one.

And the giveaway is this: the duplicate rate rises with demand. It's highest at peak
hours. That's the signature of collision under coarse resolution — not of a data fault.

So dropping them would have deleted real demand, and it would have deleted it precisely at
the busiest hours, which is exactly when the forecast matters most.

That reasoning is recorded in the artifact, along with the alternative I rejected. Not
just what I chose — what I chose *against*.
""",
        ),
        Beat(
            heading="Not shuffling the split",
            show="the split summary, with the embargo line visible",
            say=f"""
This is a time series, so the split is chronological. I train on the earlier period and
test on the later one — {split['test_days']} days held out at the end.

But there's a subtler problem, and this is the part most tutorials skip.

My features include a lag of {split['embargo_hours']} hours — demand at this hour one week
ago. Which means a training row sitting right at the boundary shares lag history with the
first test rows. The partitions aren't actually independent.

So I discard a band of {split['embargo_hours']} hours at the boundary. That's called an
embargo. {split['n_train']:,} training rows, {split['n_test']:,} test rows, and a gap
between them that belongs to neither.

And this isn't something I have to remember to do. The split function in the shared library
refuses to shuffle a temporal split, and it records the embargo in the artifact. The
defence is structural, not a habit.
""",
        ),
        Beat(
            heading="The result I did not want",
            show="the conformal coverage table, 80% row highlighted",
            say=f"""
Now the part I nearly didn't publish.

A point forecast isn't much use for staffing. You want a range. So I added conformal
prediction intervals — a method that's supposed to give you a distribution-free coverage
guarantee. Ask for {pct(c80['nominal_coverage'], 0)} coverage, get
{pct(c80['nominal_coverage'], 0)} coverage.

At the {calibrated[0]} and {calibrated[1]} levels, it held. Close enough to nominal to
call it working.

At {failed[0]}, it did not. I asked for {pct(c80['nominal_coverage'], 0)}. I got
{pct(c80['empirical_coverage'])}. That's nearly nine points short.

I could have reported only the two levels that worked. The table would have looked clean.

Instead, here's the diagnosis. Conformal prediction assumes exchangeability — that the
residuals I calibrate on look like the residuals I'll see later. Demand grew substantially
across this window. So the calibration residuals come from a quieter period than the test
residuals. The wide intervals absorb that drift. The tight one can't.

That's a real limitation of the method under trend, it's visible in the data, and it's the
kind of thing you only find if you actually check coverage instead of assuming the
guarantee holds.
""",
        ),
        Beat(
            heading="Close",
            show="the Method tab, showing recorded decisions with rejected alternatives",
            say="""
So: a model that beats a real baseline by a modest, honest margin. A leakage defence that's
enforced in code rather than remembered. And an uncertainty estimate that failed at one of
three levels, published with the reason it failed.

Every number I just said is read at runtime from a JSON file written by the pipeline. None
of them were typed by hand. If the prose and the artifact ever disagree, the artifact is
right and the prose is a bug.

Code and full write-up are in the repository. Next video, we cluster some customers — and
find out that the algorithms don't agree with each other nearly as much as you'd hope.
""",
        ),
    ]

    return project, render(
        project,
        "NYC Ride-Hail Demand",
        f"A {pct(best['skill_score_vs_baseline'])} improvement over a zero-parameter "
        f"baseline is the real result — and the prediction intervals failed at one of "
        f"three levels, which is published rather than hidden.",
        [
            f"Open **{SITE}/#/p/{SLUGS[project]}** and let the charts finish loading.",
            "Have the **Findings**, **Method (CRISP-DM)** and **Data provenance** tabs ready to switch between.",
            "Optionally open `lib/dsx/splits.py` in an editor for the embargo section.",
        ],
        beats,
    )


# ======================================================================================
# 02 — Customer segmentation
# ======================================================================================
def script_02() -> tuple[str, str]:
    project = "02_customer_segmentation"
    sel = load(project, "selection")
    ext = load(project, "segments")["external_validation"]
    prof = load(project, "profile")
    agree = sel["cross_algorithm_agreement"]
    votes = sel["consensus"]["customer_only"]["votes"]
    index_k = max(set(votes.values()), key=list(votes.values()).count)
    profiles = sorted(ext["segment_profiles"], key=lambda s: -s["conversion_rate"])
    top, bottom = profiles[0], profiles[-1]

    beats = [
        Beat(
            heading="Cold open",
            show="the segment conversion chart",
            say=f"""
Clustering is the easiest place in data science to fool yourself.

You run k-means, you get six groups, you give them names like "high value" and "at risk",
you put them on a slide, and nobody can tell you you're wrong — because there's no right
answer to check against.

So in this project I tried to make it possible to be wrong. Three different ways.
""",
        ),
        Beat(
            heading="The data",
            show="the Data provenance tab",
            say=f"""
{prof['n_customers']:,} real contact records from a Portuguese bank's direct marketing
campaigns, from the UCI machine learning repository. Real customers, real phone calls, real
outcomes.

The key thing: each record also carries whether that person actually subscribed to the
product. I deliberately kept that column *out* of the clustering. The algorithm never sees
it.

Which means I have something most clustering projects don't — an answer key the method
wasn't allowed to look at.
""",
        ),
        Beat(
            heading="Test one: does it predict something it never saw?",
            show="the conversion-by-segment table",
            say=f"""
So here's the first real test. If these segments are picking up genuine structure, they
should differ on the outcome the algorithm was blind to.

They do, and the spread is large.

The best segment converts at {pct(top['conversion_rate'], 2)}. The worst converts at
{pct(bottom['conversion_rate'], 2)}. Overall conversion across everyone is
{pct(ext['overall_conversion'], 2)}.

Chi-squared is {ext['chi2']:,.0f}, with a p-value far below any threshold you'd care about.

That's the segmentation earning its keep. Not because the clusters look tidy on a scatter
plot — because they separate an outcome nobody told the algorithm about.
""",
        ),
        Beat(
            heading="Test two: would I get the same answer twice?",
            show="the stability sweep chart",
            say=f"""
Second test, and this is the one that changed my answer.

I resampled the data {sel['n_bootstrap']} times, re-clustered each resample, and measured
how much the groupings agreed with each other using the adjusted Rand index. If a clustering
falls apart when you shake the data slightly, it was never real structure — it was noise
with a label on it.

Now, here's what makes this interesting.

The standard internal validity indices — silhouette, Calinski-Harabasz, Davies-Bouldin —
all voted for {index_k} clusters. All three of them. Unanimously.

Stability said something different, and I went with stability. I chose
k equals {sel['chosen_k']}.

Because {index_k} clusters is a geometrically tidy answer that tells you almost nothing
about a business. And the indices are measuring compactness — not reproducibility, and
certainly not usefulness.

That's a judgement call. It's recorded as one, with the alternative I rejected written down
beside it.
""",
        ),
        Beat(
            heading="Test three — and the result I did not like",
            show="the cross-algorithm agreement figures",
            say=f"""
Third test. If the structure is really in the data, then algorithms with different
assumptions should find roughly the same thing.

K-means assumes clusters are spherical and about the same size. A Gaussian mixture allows
stretched, tilted, overlapping clusters. Ward linkage builds a hierarchy by minimising
variance increase. Three genuinely different ideas about what a cluster *is*.

I ran all three and compared them.

K-means versus the Gaussian mixture: adjusted Rand index {agree['kmeans_vs_gmm']:.2f}.
K-means versus Ward linkage: {agree['kmeans_vs_agglomerative']:.2f}.

Those are moderate numbers. Not bad — but not the agreement you'd want before telling
someone these are natural groups.

Here's how I read that honestly. Roughly half the structure I'm seeing is in the data.
The other half is the spherical assumption I imposed when I picked k-means.

So the correct claim is not "here are the six customer types." The correct claim is: this
is one defensible partition, it reproduces under resampling, and it separates an outcome it
never saw. That's a useful thing. It is not a discovery of natural kinds, and I'm not going
to describe it as one.
""",
        ),
        Beat(
            heading="Close",
            show="the Method tab, decisions with rejected alternatives",
            say="""
Three tests: external validation, stability under resampling, and agreement across
algorithms. Two of them passed convincingly. The third came back moderate, and that's
reported as a limitation rather than left out.

The honest version of a clustering project includes the part where the algorithms disagree.

Next video: I implement two frequent-itemset mining algorithms from scratch, find a
189-times speed difference between them, and then throw away about ten percent of my own
results on statistical grounds.
""",
        ),
    ]

    return project, render(
        project,
        "Customer Segmentation",
        f"The segments separate an outcome the algorithm never saw "
        f"({pct(bottom['conversion_rate'], 2)} to {pct(top['conversion_rate'], 2)} "
        f"conversion) — but three algorithms only agree at ARI "
        f"{min(agree['kmeans_vs_gmm'], agree['kmeans_vs_agglomerative']):.2f}, so half the "
        f"structure is the method's assumption.",
        [
            f"Open **{SITE}/#/p/{SLUGS[project]}**.",
            "Have the conversion chart, the stability sweep and the algorithm-agreement panel located in advance — you'll move between them quickly.",
        ],
        beats,
    )


# ======================================================================================
# 03 — Market basket mining
# ======================================================================================
def script_03() -> tuple[str, str]:
    project = "03_market_basket"
    alg = load(project, "algorithms")["comparison"]
    rules = load(project, "rules")
    sig = rules["significance"]
    prof = load(project, "profile")
    top = rules["top_by_lift"][0]
    dis = rules["dissociations"][0]

    beats = [
        Beat(
            heading="Cold open",
            show="the algorithm comparison table",
            say=f"""
Two algorithms. Same data. Same output — byte for byte identical, all
{alg['n_itemsets']:,} results.

One took {alg['apriori']['seconds']:.1f} seconds. The other took
{alg['fp_growth']['seconds']:.2f}.

That's {alg['speedup_fp_over_apriori']:.0f} times faster for exactly the same answer. In
this video I'll show you where that factor comes from — and then I'll show you the part
almost nobody does, which is throwing away about ten percent of the results on statistical
grounds.
""",
        ),
        Beat(
            heading="The data and the problem",
            show="the Data provenance tab",
            say=f"""
{prof['n_transactions']:,} real grocery baskets across {prof['n_distinct_items']} product
categories. This is the classic groceries dataset from the R `arules` package — genuine
point-of-sale transactions.

The question is: which products actually pull each other into the basket? Because if you
get that right you can place them together. And if you get it wrong, you rearrange an aisle
around a pattern that was noise, which costs real money and is very hard to detect
afterwards.
""",
        ),
        Beat(
            heading="Why I wrote both algorithms by hand",
            show="the pipeline source, the Apriori and FP-Growth functions",
            say=f"""
I implemented both from first principles instead of calling a library, and I want to be
clear about why — it's not for the sake of it.

Two reasons.

First, if you call `mlxtend.apriori`, the difference between the two algorithms is hidden
inside a function, and the runtime comparison means nothing.

Second — and this is the real one — running two independent implementations on the same
data gives you something a single library call never does. **If they disagree, at least one
of them is wrong.**

They didn't disagree. All {alg['n_itemsets']:,} frequent itemsets, identical.

And the pipeline now raises an exception and refuses to write any results if they ever
diverge. That's a much stronger correctness statement than "the code ran without an error."
""",
        ),
        Beat(
            heading="Where the speedup comes from",
            show="the per-level candidate counts for Apriori",
            say=f"""
So where does {alg['speedup_fp_over_apriori']:.0f}x come from?

Apriori works level by level. It generates candidate itemsets of size one, counts them,
uses the survivors to build candidates of size two, counts those, and so on. Each level
means another full pass over the database.

It has a genuinely clever pruning rule — if any subset of a candidate is infrequent, the
candidate can't be frequent, so you can discard it before counting. And that rule works: it
eliminated {pct(alg['apriori']['pruning_rate'])} of candidates before counting.

But look at the raw volume. It still generated {alg['apriori']['candidates_generated']:,}
candidates across {alg['apriori']['database_scans']} database scans.

FP-Growth reads the database exactly {alg['fp_growth']['database_scans']} times. Once to
count how often each item appears, once to build a prefix tree where common beginnings are
shared. Then it mines that tree recursively, entirely in memory.

Candidates generated: **zero**. None. It never proposes an itemset and then checks it. It
reads them off the structure.

{alg['fp_growth']['tree_nodes_created']:,} tree nodes, and it's done.
""",
        ),
        Beat(
            heading="The part that changed the results",
            show="the FDR summary",
            say=f"""
Now here's the step that actually changed what I published.

Mining generated {sig['n_rules_tested']:,} candidate rules. The normal thing to do is sort
by lift, take the top ten, and put them on a slide.

Think about what that is statistically. With {prof['n_distinct_items']} items there are
tens of thousands of possible pairs. Test tens of thousands of hypotheses at p below
point-oh-five, and you expect *thousands* of false positives — even if nothing in the data
is associated with anything.

So every single rule got a Fisher exact test, and then a Benjamini-Hochberg correction for
multiple comparisons.

**{sig['n_rejected_by_fdr']:,} rules failed.** They're excluded from every table I publish.
{sig['n_significant']:,} survived.

I chose Benjamini-Hochberg over Bonferroni deliberately. Bonferroni controls the chance of
*any* false positive, and at this scale it would reject genuine affinities along with the
noise. Benjamini-Hochberg controls the expected *proportion* of false discoveries in the
list — which is the right guarantee when the output is a shortlist a human is going to work
through.

And because "I implemented a statistical correction" is a claim you should be suspicious
of, I checked mine against `statsmodels`. Maximum difference in q-values: about one times
ten to the minus sixteen. Identical rejection sets.
""",
        ),
        Beat(
            heading="What survived",
            show="the top rules table, then scroll to the dissociations",
            say=f"""
Here's the strongest surviving affinity: lift of {top['lift']:.1f}. And the nice thing is
it's interpretable — you can look at it and see why those products go together.

Now scroll down, because this is my favourite part.

These are *dissociations*. Pairs bought together **less** often than chance predicts.

The problem is that lift squashes all negative association into the range zero to one, so
everything down there looks about the same. Zhang's metric spans minus one to plus one and
separates them properly.

The strongest one scores {dis['zhang']:.2f} — canned beer actively repelling whole milk.
Those are two different shopping trips, the beer run and the big shop, and a merchandiser
who knows that won't waste an end-cap trying to bridge them.

One caveat I want to state out loud, because it's easy to miss. Look at the q-value column
on these rows: it reads {dis['q_value']:.1f}. That is not a mistake, and it is not evidence
*for* these rules. My significance test is a one-sided Fisher exact test — it asks whether
two items co-occur *more* than chance. A pair that co-occurs *less* than chance will always
score near one on that test, by construction.

So the dissociations are ranked by Zhang's metric, and the FDR machinery says nothing about
them either way. Certifying depletion would need the test pointed the other way. I haven't
done that, so I'm not going to claim these are statistically established — only that the
effect size is large and the interpretation is plausible.
""",
        ),
        Beat(
            heading="Close",
            show="the project README",
            say="""
Two implementations that check each other. A speedup you can trace to a specific
algorithmic idea. And a multiple-comparisons correction that removed thousands of my own
rules before I published the rest.

Next video: fraud detection, where the positive class is under two-tenths of one percent,
and where the standard textbook advice for imbalanced data made my model eighty times
worse.
""",
        ),
    ]

    return project, render(
        project,
        "Market Basket Mining",
        f"Two from-scratch implementations agree byte-for-byte on "
        f"{alg['n_itemsets']:,} itemsets at a {alg['speedup_fp_over_apriori']:.0f}x speed "
        f"difference — and {sig['n_rejected_by_fdr']:,} mined rules were thrown out for "
        f"failing FDR control.",
        [
            f"Open **{SITE}/#/p/{SLUGS[project]}**.",
            "Have `projects/03_market_basket/pipeline/build.py` open at the two algorithm implementations.",
            "Locate the dissociations table in advance — it's below the top-rules table.",
        ],
        beats,
    )


# ======================================================================================
# 04 — Fraud detection
# ======================================================================================
def script_04() -> tuple[str, str]:
    project = "04_fraud_detection"
    models = load(project, "models")
    best = models["results"][models["best"]]
    lgb = models["results"]["lightgbm"]
    iso = models["results"]["isolation_forest"]
    abl = models["reweighting_ablation"]
    none = [v for v in abl["variants"] if v["variant"] == "none"][0]
    worst = [v for v in abl["variants"] if v["variant"] == abl["worst"]][0]
    prof = load(project, "profile")["profile"]

    beats = [
        Beat(
            heading="Cold open",
            show="the headline stats, PR-AUC beside the no-skill floor",
            say=f"""
This model is {pct(best['roc_auc'])} accurate by area under the ROC curve.

And I want to start by telling you that number is close to useless here, and show you what
to look at instead.

This is credit card fraud. {prof['n_transactions']:,} real transactions, of which
{pct(prof['prevalence'], 3)} are fraudulent — {prof['n_fraud']} cases in total.
""",
        ),
        Beat(
            heading="Why accuracy and ROC both lie here",
            show="the prevalence and always-negative-accuracy figures",
            say=f"""
Start with accuracy, because it's the most dangerous number in this entire dataset.

If I write a model that returns "not fraud" for every single transaction — one line, no
training, no data — it is {pct(prof['always_negative_accuracy'], 1)} accurate.

That's not a good model. That's an arithmetic consequence of the class balance. Any metric
where doing nothing scores that well is not measuring skill.

ROC-AUC is subtler, and it's the one people get caught by. ROC plots the true positive rate
against the false positive rate. The false positive rate has the number of *negatives* in
its denominator — and here there are hundreds of thousands of them. So you can add thousands
of false alarms and barely move the curve.

The measure that doesn't have that problem is precision-recall AUC, because precision is
computed against the number of predicted positives. Add false alarms and precision falls
immediately.

So: the no-skill floor for PR-AUC is just the prevalence — {best['prevalence']:.5f}.

My best model scores {best['pr_auc']:.4f}.

That's a lift of about {best['pr_auc_lift_over_no_skill']:.0f} times over the floor. *That*
is the number worth quoting, and it's only meaningful because the floor is printed next to
it.
""",
        ),
        Beat(
            heading="Three models, and the one that won is the boring one",
            show="the model comparison table",
            say=f"""
I ran three approaches that make genuinely different assumptions.

An isolation forest — unsupervised, it doesn't use the labels at all, it just looks for
points that are easy to isolate. PR-AUC {iso['pr_auc']:.4f}.

Gradient boosting — LightGBM, fully supervised. PR-AUC {lgb['pr_auc']:.4f}.

And class-weighted logistic regression — a linear model, the simplest thing here.
PR-AUC {best['pr_auc']:.4f}.

The linear model won.

I want to sit on that for a second, because there's a lesson in it. This dataset is mostly
principal components — it's already been through PCA — and the fraud signal in it is largely
linear in that space. A more flexible model has more ways to overfit
{prof['n_fraud']} positive examples and no extra structure to exploit.

Reaching for the most powerful model available is a reflex. It's often wrong, and the only
way to know is to run the simple one too.
""",
        ),
        Beat(
            heading="The ablation — where standard advice cost me 80x",
            show="the reweighting ablation chart",
            say=f"""
Now the part I'm most glad I didn't skip.

Every guide to imbalanced classification with gradient boosting tells you the same thing:
set `scale_pos_weight` to the ratio of negatives to positives. Here that ratio is about
{worst['scale_pos_weight']:.0f}.

I did that. PR-AUC came out at {worst['pr_auc']:.4f}.

That is catastrophically bad — barely above the no-skill floor. And here's the moment that
matters: my instinct was to assume I'd made a mistake, quietly tune it until it looked
reasonable, and never mention it.

Instead I ran the whole ablation. Four configurations, all published.

With no reweighting at all: {none['pr_auc']:.4f}.

With the recommended weight of {worst['scale_pos_weight']:.0f}: {worst['pr_auc']:.4f}.

That's roughly {none['pr_auc'] / max(worst['pr_auc'], 1e-9):.0f} times worse — by following
the standard advice.

And there's a real reason. With only a few hundred positive rows in training, an extreme
weight makes every split in every tree chase the same handful of points. The trees fit those
rows, and the ranking of everything else degrades.

Notice it helped the linear model and destroyed the boosted one. A linear model's capacity
is bounded, so reweighting shifts its decision boundary. A boosted ensemble's capacity isn't
bounded, so it just memorises the upweighted rows.

The advice isn't wrong in general. It's wrong here. And the only way to know which is to run
the ablation instead of following the guidance.
""",
        ),
        Beat(
            heading="The threshold is a business decision, not a statistical one",
            show="the cost curve",
            say=f"""
One more thing, and it's the part that would actually get this deployed.

A model outputs a score. Someone has to pick the cutoff. And the default — point five —
has no justification whatsoever in a problem like this.

The right cutoff depends on relative cost. A missed fraud costs the transaction value plus
the chargeback. A false alarm costs an analyst's time and annoys a customer.

So this curve sweeps the threshold and shows total cost under different assumptions about
that ratio. There's no single optimum, because there's no single business.

What that means practically: I can't hand you a threshold. I can hand you the curve and the
question — how much is a missed fraud worth relative to a false alarm? Answer that, and the
curve gives you the cutoff.

That's the honest handoff.
""",
        ),
        Beat(
            heading="Close",
            show="the Method tab",
            say="""
So: a metric chosen because the obvious ones are misleading at this prevalence, reported
next to the floor that makes it interpretable. The simplest model winning. An ablation that
contradicts the standard advice, published because it contradicts it. And a threshold left
as the business decision it actually is.

Next video: I run the same model tournament twice — once with one extra column, and once
without it — and price exactly what a single leaked feature is worth.
""",
        ),
    ]

    return project, render(
        project,
        "Fraud Detection",
        f"PR-AUC {best['pr_auc']:.4f} against a {best['prevalence']:.5f} no-skill floor — "
        f"and the textbook reweighting advice made the boosted model about "
        f"{none['pr_auc'] / max(worst['pr_auc'], 1e-9):.0f}x worse, which is published "
        f"rather than tuned away.",
        [
            f"Open **{SITE}/#/p/{SLUGS[project]}**.",
            "Have the model table, the ablation chart and the cost curve located before you start.",
        ],
        beats,
    )


# ======================================================================================
# 05 — Forecasting tournament
# ======================================================================================
def script_05() -> tuple[str, str]:
    project = "05_timeseries_forecasting"
    syn = load(project, "synthesis")
    winners = syn["winners_by_series"]
    ranking = syn["cross_series_ranking"]
    naive_series = [k for k, v in winners.items() if "naive" in v.lower()]
    champion = ranking[0]

    beats = [
        Beat(
            heading="Cold open",
            show="the winners-by-series table",
            say=f"""
Most forecasting write-ups pick one time series, try a few models, and announce a winner.

The problem is that the answer depends almost entirely on which series you picked. So in
this project I ran {len(ranking)} forecasters across {len(winners)} structurally different
real series — and on one of them, nothing I tried beat the stupidest possible baseline.

That's the result I want to spend the most time on.
""",
        ),
        Beat(
            heading="The four series, and why these four",
            show="the four series charts",
            say=f"""
These aren't four samples of the same thing. They're four different *shapes* of problem.

{', '.join(winners).replace('_', ' ')}.

One has a clean multiplicative trend with strong yearly seasonality. One is temperature —
seasonal, but noisy and mean-reverting. One is pharmaceutical sales, with both trend and
seasonality. And one is sunspots, which is where this gets interesting.

If you only test on the first one, you'll conclude that classical seasonal models win, and
you'll be right about that series and wrong about the general case.
""",
        ),
        Beat(
            heading="The evaluation protocol",
            show="the protocol description",
            say=f"""
Every model is evaluated the same way: rolling origin.

{syn['protocol']}

That last sentence is the point. A single train-test cut is one sample of the model's
performance, and the variance between cuts is large enough to reverse a ranking. Eight
origins means a single lucky split can't decide the winner.

And the error measure is MASE — mean absolute scaled error. It's scaled by the naive
forecast's error on the training data, which means a MASE below one beats naive and above
one loses to it. The comparison is built into the metric.
""",
        ),
        Beat(
            heading="The result",
            show="the cross-series ranking table",
            say=f"""
Across all four series, {champion['label']} ranks first with a mean rank of
{champion['mean_rank']}, winning {champion['wins']} of {len(winners)}.

Which is roughly the expected answer. Classical seasonal models are strong on strongly
seasonal data, and gradient boosting — which people reach for by default now — came second
with {ranking[1]['wins']} outright wins.

But the interesting row isn't at the top.
""",
        ),
        Beat(
            heading="The series where nothing worked",
            show="the sunspots chart and its MASE table",
            say=f"""
On {', '.join(naive_series)}, the winner is **seasonal naive**. The baseline. Repeat what
happened one cycle ago.

Every learned model lost to it.

And there's a reason, which is what makes it worth publishing rather than hiding. The
sunspot cycle averages about eleven years — but it isn't fixed, and it isn't anchored to
the calendar. Cycles run long, cycles run short, amplitudes vary enormously.

A seasonal model needs a fixed period to work with. Give it a period that drifts, and the
seasonal terms fit the average cycle and then gradually fall out of phase with the actual
one. The naive forecast has no period to get wrong.

So {len(naive_series)} of {len(winners)} series where the honest conclusion is: don't use a
model here, use the baseline.

If I'd run this study on one series, I'd have written "SARIMA wins" and I'd have been
wrong about the general case. Four series is still a small sample — I want to be clear
about that too — but it's enough to show the conclusion depends on the shape of the data.
""",
        ),
        Beat(
            heading="Close",
            show="the project README",
            say="""
Six forecasters, four real series, rolling-origin evaluation, and one series where the
right answer is to not bother.

A baseline isn't there to be beaten. It's there to tell you whether the modelling was worth
doing. Sometimes the answer is no, and that's information.

Next video: the single most useful result in this whole portfolio. One column, worth forty
percent of a performance metric, invisible to every diagnostic except thinking about time.
""",
        ),
    ]

    return project, render(
        project,
        "Forecasting Tournament",
        f"{len(naive_series)} of {len(winners)} real series where no learned model beats "
        f"the naive baseline — the result a single-series study would have missed.",
        [
            f"Open **{SITE}/#/p/{SLUGS[project]}**.",
            "Have the sunspots series and its MASE table ready — that's the centrepiece.",
        ],
        beats,
    )


# ======================================================================================
# 06 — AutoML and the leak
# ======================================================================================
def script_06() -> tuple[str, str]:
    project = "06_automl_tournament"
    leak = load(project, "leak_demonstration")
    inf = leak["inflation"]
    diag = leak["diagnostic"]
    per_model = inf["per_model"]

    beats = [
        Beat(
            heading="Cold open",
            show="the clean-vs-leaked comparison",
            say=f"""
If you take one thing from this entire portfolio, I'd like it to be this video.

Same dataset. Same models. Same cross-validation. Same everything — except one column.

Without that column, the best model scores {inf['clean_best_pr_auc']:.4f}.

With it, {inf['leaked_best_pr_auc']:.4f}.

That's a {pct(inf['relative_inflation'])} improvement from a single feature. And that
improvement is completely fake. It would vanish the moment you deployed it.

Here's how to spot it.
""",
        ),
        Beat(
            heading="The column",
            show="the diagnostic panel for the leaked column",
            say=f"""
The column is called `{diag['column']}`. It's the length of the marketing phone call, in
seconds.

And the question that exposes it is the only question that matters for leakage:

**Would this value exist at the moment I have to make the prediction?**

No. It wouldn't.

The prediction I'm making is: should we call this person? If I haven't called them yet, the
call has no length. The value doesn't exist. It comes into existence *because* of the thing
I'm trying to predict.

Look at the numbers. Customers who subscribed averaged {diag['mean_duration_subscribed']:.0f}
seconds on the phone. Customers who declined averaged {diag['mean_duration_declined']:.0f}.

That's not the feature predicting the outcome. That's the outcome leaving a fingerprint on
the feature. A long call happened because it was going well.
""",
        ),
        Beat(
            heading="Why every standard diagnostic misses it",
            show="the per-model table",
            say=f"""
Now here's the part that should worry you.

That column on its own — one feature, nothing else — gets a ROC-AUC of
{diag['univariate_roc_auc']:.3f}.

A single column reaching {diag['univariate_roc_auc']:.2f} is a red flag, not a feature. But
nothing *automatically* flags it.

Cross-validation doesn't catch it, because the column is present in training and test alike.
The confusion matrix looks great. The calibration curve looks great. Learning curves look
great. Feature importance shows it at the top, which reads like a success.

And the inflation isn't limited to one model. Look at the table —
{len(per_model)} different model families, and every one of them gains:
{per_model[0]['model'].replace('_', ' ')} from {per_model[0]['clean_pr_auc']:.4f} to
{per_model[0]['leaked_pr_auc']:.4f}, and so on down the list.

The leak doesn't care what algorithm you use. It's a property of the *data*, and every
diagnostic I've listed measures how well the model fits the data.

The only thing that catches it is reasoning about *when each value becomes known*. That's
not a statistical test. It's a question you ask about every column, and it takes about ten
minutes.
""",
        ),
        Beat(
            heading="Why I ran the tournament twice",
            show="both tournaments side by side",
            say=f"""
Here's why this is set up as two full tournaments rather than one warning in a paragraph.

I could have written "don't include leaked features." Everyone has read that sentence.
Nobody changes their behaviour because of it.

What changes behaviour is a number. Running the identical pipeline twice — once clean, once
leaked — *prices* the leak. {pct(inf['relative_inflation'])} of PR-AUC. That's what it's
worth, on this data, with these models.

And note which way round it is. The clean number, {inf['clean_best_pr_auc']:.4f}, is the
honest one. It's also the less impressive one. If I were optimising for a portfolio that
looks good, I'd keep the column and never mention it — and there is genuinely no way for a
reader to tell from the outputs alone.

That's the uncomfortable part. The leaked version isn't visibly broken. It just doesn't
work in production.
""",
        ),
        Beat(
            heading="The stacking result nobody mentions",
            show="the model leaderboard",
            say=f"""
One smaller finding while we're here.

The tournament includes a stacked ensemble — the thing that wins Kaggle competitions. It
came top: {inf['clean_best_pr_auc']:.4f}.

Second place, a plain random forest: {per_model[1]['clean_pr_auc']:.4f}.

That's a difference in the fourth decimal place. For a substantial increase in complexity,
training time, and the number of things that can break in deployment.

Stacking won. Stacking was also not worth it. Both of those are true, and leaderboards only
ever report the first one.
""",
        ),
        Beat(
            heading="Close",
            show="the Method tab",
            say="""
One question — would this value exist when I have to predict? — asked of every column,
catches a class of error that no amount of cross-validation will.

It cost nothing to ask. It was worth forty percent of a metric.

Next video: I build a transformer from tensor operations, train it on a CPU, and evaluate
it against baselines that most language-model demos never show you.
""",
        ),
    ]

    return project, render(
        project,
        "AutoML & the Leak",
        f"One column that cannot exist at scoring time inflates PR-AUC from "
        f"{inf['clean_best_pr_auc']:.4f} to {inf['leaked_best_pr_auc']:.4f} — "
        f"{pct(inf['relative_inflation'])} — and no standard diagnostic flags it.",
        [
            f"Open **{SITE}/#/p/{SLUGS[project]}**.",
            "Have the clean-vs-leaked comparison and the per-model table visible.",
            "This is the flagship video — consider recording it first while you're freshest.",
        ],
        beats,
    )


# ======================================================================================
# 07 — Nano transformer
# ======================================================================================
def script_07() -> tuple[str, str]:
    project = "07_nano_transformer"
    train = load(project, "training")
    ev = load(project, "evaluation")
    best = train["best_val"]
    base = ev["baselines"]
    arch = train["architecture"]

    beats = [
        Beat(
            heading="Cold open",
            show="the generated sample text",
            say=f"""
This is text generated by a language model I wrote from tensor operations — no
`nn.Transformer`, no pretrained weights — and trained on a CPU in about
{train['train_seconds'] / 60:.0f} minutes.

It's {train['n_parameters']:,} parameters. That's small. You could fit thousands of these
inside one modern model.

And the reason I'm showing you the sample first is that a sample is the worst possible way
to evaluate a language model. It's the thing everyone shows, and it tells you almost
nothing. So after this, I'm going to show you the numbers that do.
""",
        ),
        Beat(
            heading="What's actually in it",
            show="the architecture panel",
            say=f"""
The architecture is the modern decoder stack, written out by hand.

{arch['n_layers']} layers. {arch['n_heads']} attention heads. A model dimension of
{arch['d_model']}, a feed-forward width of {arch['d_ff']}, and a context window of
{arch['context']} characters. Dropout at {arch['dropout']}.

Four pieces worth naming, because each one is a specific choice rather than a default.

**Rotary position embeddings.** Instead of adding a position vector to the input, you rotate
the query and key vectors by an angle proportional to position. The dot product between two
tokens then depends on their *relative* distance, which is the thing attention actually
wants to know.

**SwiGLU.** The feed-forward block splits into two paths, one gated by the other. It costs
more parameters per layer than a plain ReLU network and consistently performs better at the
same budget.

**Pre-normalisation.** LayerNorm goes *before* each sublayer rather than after. That keeps a
clean residual path from the loss all the way to the first layer, and it's the difference
between a deep stack training smoothly and needing a careful warmup to converge at all.

**Weight tying.** The input embedding matrix and the output projection are the same tensor.
Same vocabulary, same space — and it saves a meaningful fraction of the parameters at this
scale.
""",
        ),
        Beat(
            heading="The baselines nobody shows",
            show="the perplexity comparison",
            say=f"""
Here's the evaluation, and here's where this differs from most demos.

The measure is perplexity on held-out text — roughly, how many characters the model is
effectively choosing between at each step. Lower is better.

My model: **{base['model']['perplexity']:.3f}**.

Is that good? You cannot possibly tell, and that's the point. So here are two baselines.

A **uniform** model, which picks every character with equal probability: perplexity
{base['uniform']['perplexity']:.0f}. That's just the vocabulary size — it's what "knowing
nothing at all" scores.

A **unigram** model, which knows nothing but how often each character appears in the
corpus — no context, no order, just frequencies: perplexity
{base['unigram']['perplexity']:.3f}.

That second one is the honest bar. Beating uniform is trivial. Beating unigram means you've
learned something about *sequence*.

My model is {ev['improvement_over_unigram']:.1f} times better than unigram.

Now {base['model']['perplexity']:.2f} means something. Without those two numbers it was
decoration.
""",
        ),
        Beat(
            heading="The mistake I made and left in the record",
            show="the parameter count assertion in the source",
            say=f"""
A small confession that I think is worth including.

An earlier version of my own documentation said this model had about 2.7 million parameters.
The real number is {train['n_parameters']:,}. I'd written the docstring from a config I
later changed, and then I didn't recount.

Which is exactly the failure mode this whole repository is built to prevent — prose drifting
away from reality because nobody re-derived it.

The fix isn't "be more careful." The fix is that the expected parameter count is now derived
from the config constants and asserted at runtime. If the architecture changes and the count
doesn't match, the pipeline raises an error instead of producing a document that's quietly
wrong.

That's the general principle here: don't rely on remembering. Make the machine check.
""",
        ),
        Beat(
            heading="What it can and cannot do",
            show="the training curve and attention spans",
            say=f"""
Being clear about the limits.

This model learned character-level structure. Spelling, word shapes, the rhythm of dialogue,
speaker names followed by colons, line breaks in roughly the right places. At
{train['n_parameters']:,} parameters on one corpus, that is genuinely what you'd expect.

It has not learned meaning, facts, or long-range coherence. Read a sample past a couple of
lines and it wanders.

The best validation loss came at step {best['step']:,}, with training loss at
{best['train_loss']:.4f} against validation {best['val_loss']:.4f}. That gap is the model
beginning to memorise, which is why the checkpoint that gets evaluated is the best-validation
one rather than the last one.

The value here isn't the model. It's that every component is visible and modifiable, and
you can trace exactly what each one does.
""",
        ),
        Beat(
            heading="Close",
            show="the project README",
            say="""
A transformer from tensor operations, on a CPU, evaluated against baselines that make its
score interpretable — and a parameter count that's now asserted rather than remembered.

Next video: six interactive teaching modules built on real data, including a bias-variance
curve that refuses to be the shape the textbook promises.
""",
        ),
    ]

    return project, render(
        project,
        "Nano Transformer",
        f"Perplexity {base['model']['perplexity']:.3f} means nothing until you see the "
        f"unigram baseline at {base['unigram']['perplexity']:.1f} — "
        f"{ev['improvement_over_unigram']:.1f}x better.",
        [
            f"Open **{SITE}/#/p/{SLUGS[project]}**.",
            "Have a generated sample on screen for the cold open.",
            "Optionally open `projects/07_nano_transformer/pipeline/build.py` at the attention implementation.",
        ],
        beats,
    )


# ======================================================================================
# 08 — CRISP-DM Academy
# ======================================================================================
def script_08() -> tuple[str, str]:
    project = "08_crispdm_academy"
    bp = load(project, "backprop")
    bv = load(project, "bias_variance")
    gd = load(project, "gradient_descent")
    samp = load(project, "sampling")
    idx = load(project, "index")

    beats = [
        Beat(
            heading="Cold open",
            show="the module index",
            say=f"""
Most statistics teaching material has a problem: the figures are drawn, not computed.

You've seen the bias-variance curve — the tidy U where training error falls forever and test
error turns back up. You've seen the central limit theorem demo where the sampling
distribution is beautifully normal by n equals thirty.

In this project I computed all of those from real data instead of drawing them. And several
of them came out **not** looking like the textbook.

Those are the interesting ones, so that's where I'll spend the time.
""",
        ),
        Beat(
            heading="Gradient checking",
            show="the backpropagation module",
            say=f"""
Start with the one that behaved exactly as promised, because it's also the most immediately
useful thing in here.

This module derives backpropagation by hand for a small network —
{bp['architecture']} — trained on {bp['dataset']}.

Then it does the thing you should always do: it checks the analytic gradient against a
numerical one. Nudge a parameter up a little, nudge it down a little, see how much the loss
changed, divide. That's the derivative, approximately, with no calculus involved.

Agreement between the two: maximum relative error of
{bp['max_relative_error']:.2e}.

That's the answer you want. Correct gradients agree to around one part in ten million. If
you get an error near, say, zero point three, you have a bug — not noise, a bug.

If your network won't train, this is the first thing to run, and it takes about five lines.

There's also a nice detail in the derivation. Two terms in the chain multiply out to a very
clean expression — and that cancellation is *why* sigmoid is paired with cross-entropy. Use
squared error instead and the sigmoid derivative survives, and it goes to zero when the unit
saturates, which stalls learning. That's not a convention. It's arithmetic.
""",
        ),
        Beat(
            heading="The curve that isn't a U",
            show="the bias-variance module",
            say=f"""
Now the one that broke the textbook picture.

The bias-variance decomposition, computed on {bv['dataset']} with
{bv['n_bootstrap']} bootstrap resamples per model. Polynomial degree one through fifteen.

The textbook picture: bias falls with capacity, variance rises with capacity, and test error
is a U with the optimum in the middle.

What I got: test error is minimised at degree {bv['optimal_degree']}, and it does rise
afterwards — so far so good.

But **variance is only {pct(bv['variance_share_at_max_degree'])} of test error even at
degree fifteen**. Bias dominates the entire range. There's no regime here where variance is
the problem.

And training error is **not monotone** under bootstrap averaging. The textbook says it falls
forever as you add capacity. It doesn't, here.

Now — I want to be careful about what that means. It doesn't mean the decomposition is
wrong. It means this particular dataset and this particular model family don't produce the
canonical shape, and the canonical shape is a schematic, not a law.

Crucially, both of those departures are **detected in code**. The pipeline computes whether
training error is monotone and what share of error is variance, and reports the answer. It
doesn't assert the U and then draw one.
""",
        ),
        Beat(
            heading="Learning rates, including one that diverges",
            show="the gradient descent module",
            say=f"""
The gradient descent module, on {gd['dataset']}.

Most demonstrations show you a learning rate that's too small and one that's about right.
This one also shows you one that's genuinely broken.

At the smallest rate the trajectory crawls — it's still far from the optimum when it runs
out of steps. In the middle it converges cleanly. And at the largest rate each step
overshoots by more than it corrects, and the loss **diverges**.

Not "oscillates". Diverges — it grows without bound.

That word matters, and here's why I care. My first version of this module labelled that
trajectory "oscillates", because that's the word you expect. Then I checked the actual final
loss against the initial loss, and it had grown by a factor in the hundreds of thousands.
That's not oscillation.

So the classification is now computed from the final-versus-initial loss rather than
asserted from expectation. The label describes what the numbers did.
""",
        ),
        Beat(
            heading="The central limit theorem, slower than advertised",
            show="the sampling module",
            say=f"""
The sampling distribution module, and the rule of thumb everyone learns: n equals thirty and
you're approximately normal.

Drawing real samples from a genuinely skewed real distribution, the convergence is visibly
slower than that. At small sample sizes the shape is erratic — and I've flagged that
explicitly rather than smoothing the curve, because the erraticness is itself the lesson:
it's undersampling of a heavy tail, and it's exactly what makes small-sample inference on
skewed data unreliable.

"n equals thirty" is a rule of thumb about the *centre* of a distribution. It says very
little about the tails, and the tails are usually where the decisions get made.
""",
        ),
        Beat(
            heading="Close",
            show="the quiz sections across modules",
            say=f"""
{len(idx.get('modules', [])) or 'Six'} modules, every figure computed from real data,
including the ones that came out inconvenient.

And a limitation I'll state plainly: one dataset per concept **illustrates** a phenomenon —
it doesn't establish one. Each module says which of those it's doing. And the quizzes check
recall, not judgement, which is the skill the material is actually arguing for. That's a
real gap and it's written down as one.

Next video: I build MinHash and locality-sensitive hashing from scratch — and then compute
the exact answer as well, so I can measure what the approximation actually cost.
""",
        ),
    ]

    return project, render(
        project,
        "CRISP-DM Academy",
        f"Gradient check agrees to {bp['max_relative_error']:.1e} — and the bias-variance "
        f"curve refuses to be a U, with variance only "
        f"{pct(bv['variance_share_at_max_degree'])} of test error at maximum capacity.",
        [
            f"Open **{SITE}/#/p/{SLUGS[project]}**.",
            "Walk the modules in the order used below: backprop → bias-variance → gradient descent → sampling.",
            "The modules are interactive — move a slider on camera, it reads much better than a static chart.",
        ],
        beats,
    )


# ======================================================================================
# 09 — Sub-linear similarity search
# ======================================================================================
def script_09() -> tuple[str, str]:
    project = "09_similarity_search"
    r = load(project, "results")
    prof = load(project, "profile")["profile"]
    prep = load(project, "profile")["preparation"]
    ex = r["exact"]
    mh = r["minhash"]
    acc = mh["accuracy"]
    cfgs = r["lsh_configurations"]
    worst = cfgs[0]
    full = [c for c in cfgs if c["recall"] >= 0.999][-1]
    cheap = max((c for c in cfgs if 0.85 <= c["recall"] < 0.999),
                key=lambda c: c["speedup_vs_exact"])
    strat = [s for s in acc["stratified_by_similarity"] if s["n_pairs"] > 10]

    beats = [
        Beat(
            heading="Cold open",
            show="the recall/speed trade-off table",
            say=f"""
Here's a result I could publish about this project:

**{worst['speedup_vs_exact']:.0f} times faster** than exhaustive search.

It's true. It's also worthless, and I can prove it's worthless — because that configuration
found {pct(worst['recall'])} of the duplicates it was looking for.

This video is about the number that every locality-sensitive hashing write-up reports, and
the number almost none of them report alongside it.
""",
        ),
        Beat(
            heading="The problem and the data",
            show="the Data provenance tab",
            say=f"""
The task is entity resolution. {prof['n_distinct_company_strings']:,} distinct company name
strings, pulled from {prof['n_complaints']:,} real consumer finance complaints filed with the
US Consumer Financial Protection Bureau.

You get pairs like "United Collection Bureau" and "United Collection Bureau, Incorporated."
Same company. Two strings. And if you don't catch that, your report is quietly split in half.

Comparing everything to everything is quadratic. At this size that's
{prof['exact_pairs']:,} pairs — which is exactly the point.
""",
        ),
        Beat(
            heading="Computing the exact answer on purpose",
            show="the exact-search figures",
            say=f"""
Here's the decision that makes this project different.

{prof['exact_pairs']:,} pairs is large, but it is *not* too large. I ran it.
{ex['seconds']:.2f} seconds. It found {ex['pairs_found']:,} pairs above a Jaccard similarity
of {ex['threshold']}.

That's ground truth. Now every approximation can be scored against it.

Most write-ups skip this step, and the reason is understandable — the whole point of LSH is
to avoid the exhaustive computation. But if you never compute it, you can only report your
speedup. You cannot report what it cost you.

And if the data really is too big, subsample it. A few thousand items gives you a
ground-truth recall curve that transfers far better than no curve at all.
""",
        ),
        Beat(
            heading="How it works, briefly",
            show="the S-curve chart",
            say=f"""
Two ideas, quickly.

**MinHash.** Break each name into overlapping character
{prep['shingle_size']}-grams — so it's a set of short fragments, about
{prep['mean_shingles_per_name']:.0f} per name here. Then hash the set
{mh['n_permutations']} different ways and keep the minimum each time. The fraction of those
minima that two names share is an unbiased estimate of their Jaccard similarity. You've
turned a set comparison into a fixed-length signature.

**Banding.** Split the signature into b bands of r rows. Two items become candidates if any
single band matches exactly.

The probability of becoming a candidate is one minus, one minus s to the r, all to the b.
It's an S-curve, and the steep part sits near one over b, to the power one over r.

Which means choosing bands and rows *is* choosing where that step falls. You're not tuning.
You're placing a threshold, deliberately.
""",
        ),
        Beat(
            heading="What the approximation actually cost",
            show="the full trade-off table",
            say=f"""
So here's the table, and this is the centre of the video.

At {worst['bands']} bands by {worst['rows']} rows:
{worst['speedup_vs_exact']:.0f} times faster, {pct(worst['recall'])} recall. It missed
{worst['true_pairs_missed']:,} of {ex['pairs_found']:,} true pairs. That's the headline
number I opened with, and now you can see what it bought.

At {cheap['bands']} by {cheap['rows']}: {cheap['speedup_vs_exact']:.1f} times faster,
{pct(cheap['recall'])} recall, {cheap['true_pairs_missed']:,} missed.

At {full['bands']} by {full['rows']}: **{pct(full['recall'])} recall** — every pair — and
the speedup falls to {full['speedup_vs_exact']:.1f} times. Because getting them all requires
examining {full['candidate_pairs']:,} candidate pairs, and every one has to be verified.

That's not a tuning failure. That's the guarantee LSH offers. It's probabilistic, not
exhaustive, and if a missed pair is unacceptable in your application, you need exact search.

One detail on how I timed this: the speedups **include** verification time. LSH proposes
candidates, exact comparison disposes of them. Excluding the verification would have let me
report {ex['seconds'] / full['banding_seconds']:.1f} times instead of
{full['speedup_vs_exact']:.1f} for that last row — and that's the kind of omission that
makes a benchmark meaningless.
""",
        ),
        Beat(
            heading="Where I was wrong twice",
            show="the stratified accuracy table",
            say=f"""
Now the mistake, because I think it's more instructive than the result.

My first version reported MinHash's accuracy like this: observed standard deviation
{acc['std_error_aggregate']:.4f}, theoretical value
{1 / (mh['n_permutations'] ** 0.5):.4f}. Look how much better than theory my implementation
is.

Stop. An estimator **cannot** beat its own variance. That's not a good result. It's a bug.

And it was two bugs stacked.

First: MinHash's standard deviation is not a constant. It's the square root of s times one
minus s, over k. It's near zero for dissimilar pairs. And
{pct(acc['share_of_pairs_below_0_1'])} of randomly drawn company-name pairs are dissimilar.
So my impressive aggregate was mostly measuring pairs that are trivially easy.

Second: the figure I was comparing against — one over root k — is the rule of thumb everyone
quotes, and it is **twice** the true maximum, which is nought point five over root k, or
{acc['max_theoretical_std']:.4f} here.

Stratified by true similarity, the picture is boring and correct. In each band, observed
spread tracks theory closely — {strat[0]['observed_std']:.4f} against
{strat[0]['theoretical_std']:.4f}, {strat[-1]['observed_std']:.4f} against
{strat[-1]['theoretical_std']:.4f}.

Mean error across all sampled pairs: {acc['mean_error']:+.5f}. Unbiased, as the theory
requires.

The general lesson: if your method appears to beat its own theoretical limit, you have the
theory wrong, not a breakthrough.
""",
        ),
        Beat(
            heading="Close",
            show="the top matches table and the caveat below it",
            say="""
And one limitation that belongs right next to the results.

Ground truth here is "string similarity above a threshold" — not "genuinely the same
company." Two subsidiaries of one group can score highly. A company that rebranded entirely
scores low. So every recall figure measures agreement with exact string search, not
agreement with reality.

Next video: the COMPAS criminal risk score, where I'll show you that ProPublica and the
vendor were both right, and prove why with algebra on the real numbers.
""",
        ),
    ]

    return project, render(
        project,
        "Sub-Linear Similarity Search",
        f"{pct(full['recall'])} recall costs almost all the speedup "
        f"({full['speedup_vs_exact']:.1f}x versus {cheap['speedup_vs_exact']:.0f}x at "
        f"{pct(cheap['recall'])}) — a speedup without a recall figure is half a sentence.",
        [
            f"Open **{SITE}/#/p/{SLUGS[project]}**.",
            "The S-curve chart is interactive — click through the configurations on camera.",
            "Have the stratified accuracy table ready for the mistake section.",
        ],
        beats,
    )


# Criterion names as a person would say them out loud, rather than as artifact keys.
SPOKEN_CRITERIA = {
    "demographic_parity": "Demographic parity — equal selection rates",
    "equal_opportunity": "Equal opportunity — equal false negative rates",
    "predictive_equality": "Predictive equality — equal false positive rates",
    "calibration_ppv": "Predictive parity, or calibration — equal meaning of the label",
}


# ======================================================================================
# 10 — Fairness audit
# ======================================================================================
def script_10() -> tuple[str, str]:
    project = "10_fairness_audit"
    f = load(project, "fairness")
    own = load(project, "own_model")
    prof = load(project, "profile")
    crit = f["criteria"]
    summ = f["criteria_summary"]
    imp = f["impossibility"]
    sig = f["significance"]
    fpr = crit["predictive_equality"]["measured"]
    ppv = crit["calibration_ppv"]["measured"]
    ranked = sorted(crit.items(), key=lambda kv: kv[1]["rank_closest_to_parity"])
    groups = f["by_group"]
    acc_spread = (max(m["accuracy"] for m in groups.values())
                  - min(m["accuracy"] for m in groups.values()))

    beats = [
        Beat(
            heading="Cold open",
            show="the per-group metrics table",
            say=f"""
In 2016 ProPublica published an investigation of COMPAS — a risk score used in American
courtrooms to inform bail and sentencing — and concluded it was biased against Black
defendants.

Northpointe, the company behind it, replied that the score was calibrated and therefore was
not biased.

That reads like a factual dispute. One of them must be wrong.

Neither of them was. And in this video I'm going to show you the arithmetic that makes both
statements true at the same time — computed on the real data, not quoted from a paper.
""",
        ),
        Beat(
            heading="The data",
            show="the Data provenance tab",
            say=f"""
This is ProPublica's own COMPAS release for Broward County, Florida.
{prof['rows_raw']:,} records, reduced to {prof['rows_after_propublica_filters']:,} by their
published screening filters — which I've applied as they specified rather than inventing my
own.

I'm restricting comparisons to the {len(prof['groups_compared'])} groups with at least
{prof['min_group_size']} members. The smaller groups —
{', '.join(g['group'] + ' at ' + str(g['n']) for g in prof['groups_too_small_to_compare'])}
— are excluded, and reported as excluded, because error rates on a handful of people come
with intervals too wide to interpret.

I want to name that exclusion as a finding in itself: the smallest groups are the ones least
likely to be audited anywhere, and that's a structural gap, not housekeeping.
""",
        ),
        Beat(
            heading="ProPublica's claim, measured",
            show="the FPR column",
            say=f"""
Here's the first claim. Among defendants who did **not** go on to reoffend within two
years — people the tool got wrong — how often were they labelled high risk?

{fpr['max_group']} defendants: {pct(fpr['max'])}.

{fpr['min_group']} defendants: {pct(fpr['min'])}.

That's a ratio of {fpr['ratio']:.2f} to one. A chi-squared test on the two largest groups
gives {sig['chi2']:.0f}, with a p-value around {sig['p_value']:.0e}.

That is not sampling noise. ProPublica's claim is correct.
""",
        ),
        Beat(
            heading="Northpointe's reply, also measured",
            show="the PPV column",
            say=f"""
Now the other claim. Among the people the tool labelled high risk, how many actually
reoffended?

The range across groups is {pct(ppv['min'])} to {pct(ppv['max'])}. A gap of
{ppv['absolute_difference']:.3f}.

So a "high risk" label means close to the same thing whoever receives it. That's what
calibration means, and on this data it largely holds.

Northpointe's claim is also correct.

Both tables come from the same {prof['rows_after_propublica_filters']:,} rows. Nobody was
lying. Nobody made an arithmetic error.
""",
        ),
        Beat(
            heading="Why both can be true",
            show="the impossibility section",
            say=f"""
Here's the resolution, and it's algebra.

For any classifier at all, within any group, this identity holds:

False positive rate equals — p over one minus p — times — one minus PPV, over PPV — times
one minus the false negative rate.

Where p is that group's base rate: the share who actually did reoffend.

I didn't want to cite that. I wanted to check it. So I computed the right-hand side from the
observed counts and compared it to the observed false positive rate.

Maximum discrepancy across every group: **{imp['max_identity_discrepancy']:.1e}**.

That's floating-point rounding. The identity holds exactly.

Now read it again. If two groups have different base rates — and here they differ by
{imp['base_rate_gap']:.4f} — then holding PPV equal **forces** the false positive rates to
differ.

Not because of bad data. Not because of a biased vendor. Not because of a fixable modelling
choice. Because of arithmetic.

You can equalise error rates, or you can equalise predictive value. You cannot do both. That
result is Kleinberg and colleagues in 2016, and Chouldechova in 2017 — and what you're
looking at is it, verified on the actual counts.
""",
        ),
        Beat(
            heading="The column to ignore",
            show="the accuracy column",
            say=f"""
Quick aside, because it explains how this dispute stayed alive.

Look at accuracy. It varies by only about {acc_spread * 100:.1f} percentage points across
groups.

So a vendor can report accuracy, truthfully, and sound fair. A single accuracy number
averages a false positive and a false negative into one figure — and here those two errors
land on *different people*. That's precisely the information accuracy destroys.
""",
        ),
        Beat(
            heading="The obvious fix, tested",
            show="the own-model comparison table",
            say=f"""
So the first thing everybody proposes: just don't give the model race.

I tested it. I trained a replacement model on {len(own['features_used'])} features — age,
prior convictions, charge degree, juvenile counts — with race **excluded entirely**. The
model never sees it.

COMPAS's false positive rate gap: {own['compas_fpr_gap']:.4f}.

My model's gap, with race never seen:
**{own['fpr_gap']:.4f}**.

About {pct(1 - own['fpr_gap'] / own['compas_fpr_gap'], 0)} of the gap closed. The rest
stayed.

Because prior arrest counts carry the information race would have carried. You cannot delete
a variable out of a correlated world. This has a name — fairness through unawareness — and
this is the demonstration that it doesn't work.

And I report my model against its own no-skill floor, same as everywhere else here: PR-AUC
{own['overall']['pr_auc']:.4f} against a prevalence floor of
{own['overall']['pr_auc_no_skill']:.4f}.
""",
        ),
        Beat(
            heading="The table I nearly published",
            show="the criteria ranking table",
            say=f"""
One more thing, about presentation, because I got this wrong first.

My initial criteria table had four rows and one column: VIOLATED, VIOLATED, VIOLATED,
VIOLATED. All four fairness criteria failed at a strict tolerance. Every word of it true.

And completely useless — because it erased the distinction the entire public argument was
about.

Ranked by distance from parity instead:

{chr(10).join(f"{c['rank_closest_to_parity']}. {SPOKEN_CRITERIA.get(k, k)} — gap {c['gap']:.4f}." for k, c in ranked)}

The furthest criterion is {summ['ratio_furthest_to_closest']:.2f} times further from parity
than the closest one. *That ordering* is the argument. A pass/fail column deletes it.
""",
        ),
        Beat(
            heading="Close",
            show="the limitations section",
            say="""
And the limitation that has to be said in the same breath as every number above.

All of this treats a **recorded re-arrest within two years** as ground truth for "committed
another crime". Policing is not uniform across neighbourhoods or groups. So the base rates
that drive the impossibility result are themselves measured through a process that may be
biased.

Nothing in this analysis — or in any analysis of this dataset — can separate those two
things. A gap in measured base rates is not proof of a gap in underlying behaviour.

That's not a footnote. It's the boundary of what the data can support.

Next video: I build a DAG scheduler from scratch and then measure that my own pipeline
doesn't need one.
""",
        ),
    ]

    return project, render(
        project,
        "Fairness Audit · COMPAS",
        f"Both ProPublica and Northpointe were right — FPR {pct(fpr['max'])} versus "
        f"{pct(fpr['min'])} alongside near-equal PPV — and the identity forcing that "
        f"is verified on the real counts to {imp['max_identity_discrepancy']:.0e}.",
        [
            f"Open **{SITE}/#/p/{SLUGS[project]}**.",
            "Switch the group selector on camera during the contingency-table section.",
            "This is the most sensitive subject in the portfolio — read the limitations beat slowly and do not cut it.",
        ],
        beats,
    )


# ======================================================================================
# 11 — Pipeline DAG engine
# ======================================================================================
def script_11() -> tuple[str, str]:
    project = "11_pipeline_dag"
    g = load(project, "graph")
    s = load(project, "scheduling")
    e = load(project, "engine")
    cp = s["critical_path"]
    dom = s["dominant_task"]
    cache = e["caching"]
    cyc = e["cycle_detection"]
    last = s["schedules"][-1]
    two = s["schedules"][1]
    n_pipelines = len([n for n in g["nodes"] if n["kind"] == "pipeline"])

    beats = [
        Beat(
            heading="Cold open",
            show="the speedup-vs-workers chart",
            say=f"""
Every article about workflow orchestration ends the same way: express your pipeline as a
graph, add workers, go faster.

I wrote the scheduler. Then I measured it on my own repository.

Two workers: {two['speedup']:.2f} times faster. Sixteen workers:
{last['speedup']:.2f} times faster.

That's the same number. Sixteen workers bought me nothing over two, and this video is about
why — and about how you can know that *before* you build the orchestration.
""",
        ),
        Beat(
            heading="The graph",
            show="the topological levels panel",
            say=f"""
The graph is this repository's own build. {g['n_tasks']} tasks, {g['n_edges']} edges: a
shared library, {n_pipelines} analysis pipelines, and the tooling that turns their output
into a website.

The edges are real data dependencies. A pipeline depends on the library it imports. The
artifact sync depends on every pipeline. The site build depends on the sync. Screenshots
depend on the site build.

Run it one task at a time: {g['total_sequential_seconds']:.0f} seconds.

Sorting it gives {g['n_levels']} levels, and the widest holds {g['max_width']} tasks.
{g['max_width']} things that can run at once! This is the moment the blog post tells you to
spin up sixteen workers.
""",
        ),
        Beat(
            heading="Why Kahn's algorithm and not depth-first",
            show="the levels list",
            say=f"""
Quick but important point about the sort.

A depth-first topological sort gives you one valid linear ordering. It's correct, and it
throws away the thing you actually need — it tells you a legal sequence, not what can happen
simultaneously.

Kahn's algorithm peels the graph off in layers. Take everything with no remaining
dependencies, that's layer zero. Remove it, repeat.

The **width of each layer is the available parallelism**. That's the number a scheduler
consumes, and it only exists if you sort this way.
""",
        ),
        Beat(
            heading="The critical path, which ends the discussion",
            show="the critical path bar chart",
            say=f"""
Here's the number I'd compute before writing a single line of scheduler.

The critical path is the longest chain of tasks that must happen in order. Nothing can
finish before it completes — at any worker count, with any scheduler, ever.

Here it's {cp['seconds']:.0f} seconds, against {s['sequential_seconds']:.0f} sequential.

So the ceiling is {s['sequential_seconds']:.0f} divided by {cp['seconds']:.0f} —
**{s['theoretical_max_speedup']:.2f} times**. That's the maximum. Full stop.

And here is the whole story in one row: the task `{dom['name']}` takes
{dom['seconds']:.0f} seconds, which is **{pct(dom['share_of_critical_path'])} of the
critical path**.

It's the transformer from video seven, training on a CPU. Everything else in this repository
put together is a few minutes. No scheduler can parallelise a single task with itself.

Now reframe the opening number. {two['speedup']:.2f} times sounds disappointing — until you
know the maximum is {s['theoretical_max_speedup']:.2f}. Then it's
{pct(two['speedup'] / s['theoretical_max_speedup'], 0)} of what's achievable.

A scheduling result cannot be interpreted in *either* direction without its ceiling printed
next to it. That's the same argument as the no-skill baseline, applied to systems work.
""",
        ),
        Beat(
            heading="The number to take to a budget meeting",
            show="the scheduling table, idle capacity column",
            say=f"""
Look at the idle column at {last['workers']} workers:
{pct(last['idle_fraction_of_capacity'], 0)} of the fleet is doing nothing, and the makespan
is within a second or so of the two-worker result.

One note on how that's measured. Raw idle *worker-seconds* grow automatically with fleet
size — a bigger fleet idles more by definition — so quoting them makes the problem look like
it's getting worse when nothing has changed. This is idle divided by available capacity,
which is comparable across worker counts.

An earlier version of this project reported the raw figure and it was genuinely misleading,
so it's now named and normalised.
""",
        ),
        Beat(
            heading="Two pieces I'd keep",
            show="the cycle detection message, then the fingerprint table",
            say=f"""
Two parts of the engine I think are worth stealing regardless.

**Cycle detection that names the cycle.** Most implementations raise "cycle detected". On a
hundred-node graph, that's barely better than silence. Mine does a tri-colour depth-first
search: an edge into a node that's currently in progress closes a cycle, and the stack
between them *is* the cycle. So it reports:

{cyc['message']}

That's a debuggable error message.

**Caching that chains through dependencies.** A task's fingerprint is a hash of its own
content **plus the fingerprints of everything it depends on**. Because the hash chains,
invalidation is transitive by construction — no separate graph walk, no bookkeeping to get
out of sync.

I tested it by perturbing the shared library:
**{cache['n_invalidated']} of {cache['n_total']} tasks invalidated.** Everything, correctly,
because every pipeline imports it.
""",
        ),
        Beat(
            heading="Close",
            show="the limitations section",
            say=f"""
Two honest caveats.

My scheduler releases tasks in levels, with a barrier between them. A real work-stealing
executor starts a task the moment its own dependencies finish, so my speedups are a **lower**
bound on what Airflow or Dagster would achieve.

That doesn't rescue the conclusion, though — the {s['theoretical_max_speedup']:.2f} times
ceiling binds them too. Better scheduling cannot shorten a chain.

And these durations come from one machine, one run. On a machine with a GPU the dominant task
collapses and the critical path runs through completely different tasks. The method
transfers. The seconds don't.

If you want this build faster there is exactly one move: make that one task cheaper, or cache
it. Writing the scheduler was the fun part. The profiler was the useful one.

Last video: a trading strategy that finds nothing, and why that's the point.
""",
        ),
    ]

    return project, render(
        project,
        "Pipeline DAG Engine",
        f"The critical path caps speedup at {s['theoretical_max_speedup']:.2f}x at any "
        f"worker count, because one task is {pct(dom['share_of_critical_path'])} of it — "
        f"so {two['speedup']:.2f}x is near-optimal, not disappointing.",
        [
            f"Open **{SITE}/#/p/{SLUGS[project]}**.",
            "Click through the worker-count selector on camera — the flat curve is the whole argument.",
            "Have the cycle-detection message and the fingerprint table located in advance.",
        ],
        beats,
    )


# ======================================================================================
# 12 — Market backtest
# ======================================================================================
def script_12() -> tuple[str, str]:
    project = "12_market_backtest"
    r = load(project, "results")
    profile = load(project, "profile")
    p = profile["profile"]
    prep = profile["preparation"]
    trap = profile["random_walk_trap"]
    look = prep["lookahead_test"]
    v = r["verdict"]
    names = list(r["results"])
    bench = v["benchmark_net"]
    folds = [f["directional_accuracy"] for n in names for f in r["results"][n]["folds"]]

    beats = [
        Beat(
            heading="Cold open",
            show="the two R-squared cards side by side",
            say=f"""
Here's a model I could have led with.

**R-squared of {trap['r2_predicting_price_with_yesterdays_price']:.4f}** predicting
tomorrow's Apple share price.

That looks publishable. It is repeating yesterday's price.

Here is the identical model, restated as a forecast of tomorrow's **return**:

**R-squared of {trap['r2_predicting_return_with_zero']:.4f}**.

Same model. Same data. Same information content — which is none.

This is the project where nothing worked, and that is exactly why it's here.
""",
        ),
        Beat(
            heading="Why the first number is an artefact",
            show="the stationarity figures",
            say=f"""
The reason the first number is meaningless is that prices are non-stationary. They wander.
Today's price is the best single guess for tomorrow's, so a model that just repeats it
explains almost all the variance — and predicts nothing.

The statistical version: an augmented Dickey-Fuller test rejects a unit root in *returns*,
with p of {p['stationarity']['returns_adf_pvalue']:.4f}, and fails to reject it in *price*,
p of {p['stationarity']['price_adf_pvalue']:.3f}.

So the target has to be returns. Modelling price directly means fitting a regression that
assumes stationarity to a series that isn't.

If you have ever seen a financial machine-learning post with a stunning R-squared and a
chart of predicted-versus-actual prices hugging the diagonal — that's what you were looking
at.
""",
        ),
        Beat(
            heading="The setup",
            show="the sample facts table",
            say=f"""
{p['n_days']:,} daily bars of Apple, {p['date_min']} to {p['date_max']}.
{prep['n_features']} features — lagged returns, momentum, realised volatility, RSI, a volume
z-score — predicting the {prep['horizon_days']}-day forward return. Two models: ridge
regression and gradient boosting.

One detail that matters: I'm using **adjusted** closes. Adjusted and unadjusted differ by up
to {pct(p['max_adjustment_vs_close'])} over this window, and using unadjusted prices would
insert a fake negative return at every dividend date — which a momentum feature reads as
signal.
""",
        ),
        Beat(
            heading="Measure signal before you measure money",
            show="the information coefficient table",
            say=f"""
Now the step that should come first in every study like this, and usually doesn't.

Before building any trading rule, before plotting any equity curve: **do the predictions
correlate with what actually happened?**

That's the information coefficient — the rank correlation between prediction and realised
return.

{chr(10).join(f"{n}: {r['results'][n]['information_coefficient']:+.4f}, with a p-value of {r['results'][n]['ic_p_value']:.3f}." for n in names)}

Both negative. Both with p-values above nought point nought five. Directional accuracy:
{', '.join(pct(r['results'][n]['directional_accuracy']) for n in names)} — against a coin
flip at fifty percent.

There is no signal here. Everything after this point is arithmetic on noise.

And that's the discipline: an equity curve built from predictions with no measurable skill
will *sometimes look excellent* by chance. Checking the IC first is what stops you
publishing that.
""",
        ),
        Beat(
            heading="The backtest anyway",
            show="the equity curves with the cost toggle",
            say=f"""
I ran the backtest regardless, because the protocol is the point.

Net of {v['cost_bps']:.0f} basis points of round-trip costs:

{chr(10).join(f"{c['strategy']}: annualised {pct(c['net_annualised'])}, Sharpe {c['net_sharpe']:.3f}." for c in v['comparison'])}

Buy and hold over the same window: {pct(bench['annualised_return'])} annualised, Sharpe
{bench['sharpe']:.3f}.

Both strategies lost to doing nothing. Both lost money outright. And both were already losing
**before** I charged any costs — so costs aren't the reason this failed, though they're the
reason a study that looks marginally profitable gross usually isn't worth running.

Watch that toggle: gross to net. {v['breakeven_note']}
""",
        ),
        Beat(
            heading="Purged cross-validation",
            show="the fold tables",
            say=f"""
Two things about the validation.

First: the folds are chronological and expanding. Fold one trains on the earliest data and
tests on what comes next. No model ever sees its own future.

Second, and subtler: my target is a {prep['horizon_days']}-day forward return, computed
every day. So consecutive rows share {prep['horizon_days'] - 1} days of outcome. Adjacent
rows are nearly the same observation.

Chronological ordering alone doesn't fix that. The row just before the test boundary overlaps
with the row just after it. So the cross-validation **purges** a band around every boundary
and throws those rows away.

And look at the fold-to-fold variation: directional accuracy swings from {pct(min(folds))} to
{pct(max(folds))} across folds of the same model.

Any single fold could be quoted as a triumph or a disaster. That range is exactly why fixing
the protocol in advance matters — after seeing that spread, I could pick a story.
""",
        ),
        Beat(
            heading="Proving there's no look-ahead",
            show="the perturbation test panel",
            say=f"""
This is the part I'm most pleased with.

My own static leakage scanner flagged two features in this pipeline. I could have written a
comment saying "this is fine, trust me." Comments aren't evidence.

So the pipeline proves it instead. The test: take every future price and volume bar from row
{look['cut_row']} onward and **multiply them by 1.5**. Rebuild the entire feature matrix from
scratch. Then check every feature value at every one of the {look['n_rows_checked']} rows
*before* the cut.

If any of them moved, that feature is reading the future.

**Maximum drift: {look['max_drift']:.1f}.** Nothing moved. Not one bit, across
{look['n_features_checked']} features.

And that test runs inside the pipeline on every execution. So a future edit that introduces
look-ahead fails the run, instead of producing a better-looking Sharpe ratio.

That's what "no look-ahead" should mean: a measurement, not an assurance.
""",
        ),
        Beat(
            heading="Close",
            show="the limitations section",
            say=f"""
So: no signal, no edge, no profit. Published as the result.

And I want to be careful about what this does *not* establish. One instrument, one two-year
window. Finding nothing here is evidence about this sample — not about momentum, or machine
learning, or equities in general. A study claiming it had *found* an edge on this same sample
would be making the much stronger and far less defensible claim.

Apple was also chosen with hindsight — it exists today and had a liquid history — which makes
buy-and-hold harder to beat than a fair universe would.

The value here isn't the models. It's the protocol:

Check the target is stationary before modelling it. Measure signal before returns. Purge
overlapping labels. Charge costs and show gross beside net. Benchmark against doing nothing.
Prove the absence of look-ahead by perturbing the future.

And then publish the result you got.

That last step is the hard one — and it's the one that makes the other six worth doing.

That's the twelfth and last project. Everything is in the repository: the code, the
artifacts, the audit, and the numbers behind every claim in all twelve of these videos.
Thanks for watching.
""",
        ),
    ]

    ic_list = ", ".join(
        f"{r['results'][n]['information_coefficient']:+.4f}" for n in names
    )
    return project, render(
        project,
        "Market Backtest",
        f"Information coefficients of {ic_list} — no measurable signal, reported as the "
        f"finding rather than tuned away.",
        [
            f"Open **{SITE}/#/p/{SLUGS[project]}**.",
            "Toggle gross/net on the equity curves on camera.",
            "Have the perturbation-test panel ready — it's the strongest part of the video.",
        ],
        beats,
    )


GENERATORS = [
    script_01, script_02, script_03, script_04, script_05, script_06,
    script_07, script_08, script_09, script_10, script_11, script_12,
]


def index(written: list[tuple[str, str, int]]) -> str:
    rows = "\n".join(
        f"| {project[:2]} | [{title}](./{project}.md) | ~{runtime} |"
        for project, title, runtime in
        [(p, t, r) for p, t, r in written]
    )
    return f"""# Video scripts

One script per project — {len(written)} separate videos, each standing on its own.

Every figure spoken in these scripts is read from a committed artifact by
[`tools/video_scripts.py`](../../tools/video_scripts.py), the same way the READMEs and the
site are generated. Re-run a pipeline and the scripts update, so what you say on camera
cannot drift away from what is on screen behind you.

| # | Script | Runtime |
|:---:|---|---|
{rows}

## How these are written

- **Plain text is spoken.** Lines marked *On screen* and *Note to self* are directions.
- **One idea per sentence**, because a listener cannot re-read a clause.
- **Numbers are said the way you'd say them aloud**, not read off like a table.
- Each script opens with a **hook** and closes by **handing off to the next video**, so the
  twelve work as a series as well as individually.
- Each one contains at least one **thing that went wrong** — a wrong claim corrected, a
  result that disagreed with expectation, or a limitation that cannot be engineered away.
  That is the argument of the portfolio, and it is what makes a walkthrough worth watching
  rather than a tour of green checkmarks.

## Suggested recording order

Record **06 · AutoML & the Leak** first. It is the strongest single idea in the portfolio
and the one most worth getting right while you are fresh. Record **01** second, since it
establishes the baseline argument that every later video leans on.

## Regenerating

```bash
python3 tools/video_scripts.py
```
"""


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    written: list[tuple[str, str, int]] = []
    total_words = 0

    for generator in GENERATORS:
        project, content = generator()
        path = OUT / f"{project}.md"
        path.write_text(content)

        title = content.splitlines()[0].split("·", 1)[1].strip()
        runtime = content.split("**Estimated runtime:** ~")[1].split(" ")[0]
        words = int(content.split("(")[1].split(" spoken")[0].replace(",", ""))
        total_words += words
        written.append((project, title, runtime))
        print(f"  {path.relative_to(ROOT)}  (~{runtime}, {words:,} words)")

    (OUT / "README.md").write_text(index(written))
    minutes = total_words / SPEAKING_WPM
    print(f"\nWrote {len(written)} scripts + an index to {OUT.relative_to(ROOT)}")
    print(f"{total_words:,} spoken words total — about {minutes / 60:.1f} hours of video "
          f"at {SPEAKING_WPM} words per minute.")
    print("Every figure spoken was read from a committed artifact.")


if __name__ == "__main__":
    main()
